### PR TITLE
Drop maxdevices test

### PR DESCRIPTION
**Pull request by mayfield**

### CODE REVIEW

**Comment by chriswil-codev** [comment]
Looks good.  How does one "approve" a PR in this system?

**Comment by mayfield** [comment]
Just by hitting merge.  I can do it  if you don't have rights.

**Comment by mayfield** [comment]
image
Yeah, you don't have perms I think.

**Comment by chriswil-codev** [comment]
K.  I also sent a message to Jeff/Jen about the issue with heroku needing to reprovision the Dev-App (they have Admin rights, where I only have Member at the moment).

**Pull request merged**
