### PR TITLE
Heroku merge

### PR DESCRIPTION
**Pull request by chriswil-codev**
Integrate Justin's and my work into a heroku minimal build

### CODE REVIEW

**Comment by mayfield** [comment]
There are quite a few unused files in here and refs to local maven repo thing.  Can we drop those now that the WebsocketResource is updated?

**Comment by chriswil-codev** [comment]
I would love to remove the local repro for websocket, but was hoping to do that in another ticket (pass).  This one is working as a base, and I like your solution to use a websocket-resource that is pulled down from a master maven repro rather than local.  What are the other unused files?  I can remove those.

**Comment by mayfield** [comment]
Gotcha.  I didn't look close enough to see that this was not pulling the new websocket version.. As soon as this is done do I need to cherry pick my PartnerAuth stuff over?

**Comment by chriswil-codev** [comment]
yes...I was hoping to do these in discrete steps so that each check-in is specific to a particular focus.  Thus, Partner-API would be a good integral check-in separate from just getting textsecure too boot in heroku.

**Comment by chriswil-codev** [comment]
I think all you're work in the other (2) PR's will fold in, but maybe in separate deliverables (?).

**Comment by mayfield** [comment]
Ok.  Looks like there is a merge conflict.  Can you fix that?

**Comment by chriswil-codev** [comment]
fixed conflict

**Pull request merged**
