### PR TITLE
Partner API for provisioning vis CCSM

### PR DESCRIPTION
**Pull request by mayfield**

### CODE REVIEW

**Comment by jeffbuttars** [comment]
fun times

**Comment by chriswil-codev** [comment]
wow, this will take me some time to digest.  The modifications to the makefile look like it is specific to running on a localVM (e.g. the ACCOUNT_DATABASE_URL and MESSAGE_DATABASE_URL which point to localhost).  Is this actually running on Heroku?  or is it just the necessary changes to get in on AWS with the intent of normalizing for Heroku?  I see that this pull-request looks very similar to the "Heroku Support" one, with added files.  Should this just be one pull-request (from mayfield:master) or from (mayfield:partnerrequest)?

Also, I need to understand the code-changes that were in place.

One thing that would be nice if we could keep enhancments in separate files as not to pollute the existing signal code-base.  It would help if/when we decide to catch-up the codebase from last trunk.

**Comment by chriswil-codev** [comment]
I certainly don't want to slow down the feature development that needs to take place between the devices/ccsm/text-secure, so is the intention to publish this to AWS and work on the Heroku code as a one-off, or is it that we want to take this code and make it the top-of-trunk for heroku even.

**Comment by mayfield** [comment]
@chriswil-codev I didn't see your PR before doing this this weekend so there is some duplication on the heroku support itself. I went the route of updating the broken WebSocket maven dep to a working one and then making the code base support the new libs.   Also this fixes Redis support which has to support authentication.  

The makefile is to streamline build and run, and is used for all envs.  This PR works for me in all envs and is actually running on prod now.

Regarding the PRs and their separation.  This one is based on the heroku patch but is mostly about a service/partner APIs (for use by CCSM only) for onboarding new accounts/devices.  From discussion today we're going to use this partner auth channel to register new devices securely by CCSM itself instead of the device doing so on the open web.

**Comment by chriswil-codev** [comment]
OK..So should this become the new master,and we remove the other PR?  Since this is providing additional work other than heroku bootstrap, we may as well take it and begin from there.  I had solved the Websocket dependency issue by incorporating a local-maven-repo where our build websocket-resource was checked into the source-repro (this fixed the build errors for me).  If your fix is more dynamic/flexible, the I'm good with that instead.  I also found when running the review-app that it had complained about pushserver not running.  Now it is deployed to DEV and should get past that failure.

**Comment by misskniss** [comment]
Closing this since Chris is not yet using it but will harvest from them later...

**Pull request closed without merging**
