### PR TITLE
No such thing as MASTER_ID / Kill v1/keys

### PR DESCRIPTION
**Pull request by mayfield**
Kill off the notion of a MASTER_ID (1).  The v1/keys controller which we
don't use was particularly embedded with this notion so I killed it off
too.

### CODE REVIEW

**Comment by mayfield** [comment]
Let me merge, this looking for feedback on killing device id 1 first and foremost.

**Review by mdescalzo — APPROVED** [review]
Reviewing the iOS code, I don't believe this will break the client.  There is a certain level of resilience built into device #s.  This will need to tested in the Dev environment to validate.

**Comment by mayfield** [comment]
Thanks @mdescalzo ;  I just reviewed the java code bases and didn't see any red flags either.   It might work.  Perhaps we can schedule a test next week.

**Comment by misskniss** [comment]
@mdescalzo and @mayfield You two may want to have a look at this interaction again. Users cannot register in the iOS app..they are getting the following error on registration:

(Note: Stage and Prod versions are working fine.)

**Pull request merged**
